title = "Neptun-IA"
baseURL = "https://neptunia.uniparthenope.it"
languageCode = "en-us"
theme = "ananke"

DefaultContentLanguage = "it"
SectionPagesMenu = "main"

Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    languageName="English"
    weight = 1
    contentDir = "content/en"
  [languages.it]
    languageName="Italian"
    weight = 2
    contentDir = "content/it"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  cover_dimming_class = "bg-black-40"
  favicon = ""
  site_logo = ""
  description = "Multidisciplinary Research Laboratory for the Artificial Intelligence at the Sea"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/neptunia-dist"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  #featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
  recent_projects_number = 10
  mainSections = ["projects"]
